/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Head.java
 *
 * Created on 2009-11-25, 16:12:21
 */

package test.form;

/**
 *
 * @author yihaodian
 */
public class Head extends javax.swing.JPanel {

    /** Creates new form Head */
    public Head() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_Hide = new javax.swing.JLabel();
        lb_Maxi = new javax.swing.JLabel();
        lb_Mini = new javax.swing.JLabel();
        lb_Icon = new javax.swing.JLabel();
        lb_Text = new javax.swing.JLabel();

        lb_Hide.setText("jLabel1");

        lb_Maxi.setText("jLabel2");

        lb_Mini.setText("jLabel3");

        lb_Icon.setText("jLabel4");

        lb_Text.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_Icon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_Text, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_Mini)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_Maxi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_Hide)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_Hide)
                    .addComponent(lb_Maxi)
                    .addComponent(lb_Mini)
                    .addComponent(lb_Icon)
                    .addComponent(lb_Text))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lb_Hide;
    private javax.swing.JLabel lb_Icon;
    private javax.swing.JLabel lb_Maxi;
    private javax.swing.JLabel lb_Mini;
    private javax.swing.JLabel lb_Text;
    // End of variables declaration//GEN-END:variables

}
