//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1873
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.amonsoft.exts.exts0001 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfBase64Binary", Namespace="http://amonsoft.cn/exts/", ItemName="base64Binary")]
    [System.SerializableAttribute()]
    public class ArrayOfBase64Binary : System.Collections.Generic.List<byte[]> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://amonsoft.cn/exts/", ConfigurationName="exts0001.Exts0001Soap")]
    public interface Exts0001Soap {
        
        // CODEGEN: 命名空间 http://amonsoft.cn/exts/ 的元素名称 user 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://amonsoft.cn/exts/exts", ReplyAction="*")]
        com.amonsoft.exts.exts0001.extsResponse exts(com.amonsoft.exts.exts0001.extsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class extsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="exts", Namespace="http://amonsoft.cn/exts/", Order=0)]
        public com.amonsoft.exts.exts0001.extsRequestBody Body;
        
        public extsRequest() {
        }
        
        public extsRequest(com.amonsoft.exts.exts0001.extsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://amonsoft.cn/exts/")]
    public partial class extsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwds;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string exts;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string mime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string desp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public com.amonsoft.exts.exts0001.ArrayOfBase64Binary file;
        
        public extsRequestBody() {
        }
        
        public extsRequestBody(string user, string pwds, string exts, string mime, string desp, com.amonsoft.exts.exts0001.ArrayOfBase64Binary file) {
            this.user = user;
            this.pwds = pwds;
            this.exts = exts;
            this.mime = mime;
            this.desp = desp;
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class extsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="extsResponse", Namespace="http://amonsoft.cn/exts/", Order=0)]
        public com.amonsoft.exts.exts0001.extsResponseBody Body;
        
        public extsResponse() {
        }
        
        public extsResponse(com.amonsoft.exts.exts0001.extsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://amonsoft.cn/exts/")]
    public partial class extsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool extsResult;
        
        public extsResponseBody() {
        }
        
        public extsResponseBody(bool extsResult) {
            this.extsResult = extsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface Exts0001SoapChannel : com.amonsoft.exts.exts0001.Exts0001Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class Exts0001SoapClient : System.ServiceModel.ClientBase<com.amonsoft.exts.exts0001.Exts0001Soap>, com.amonsoft.exts.exts0001.Exts0001Soap {
        
        public Exts0001SoapClient() {
        }
        
        public Exts0001SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Exts0001SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Exts0001SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Exts0001SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.amonsoft.exts.exts0001.extsResponse com.amonsoft.exts.exts0001.Exts0001Soap.exts(com.amonsoft.exts.exts0001.extsRequest request) {
            return base.Channel.exts(request);
        }
        
        public bool exts(string user, string pwds, string exts1, string mime, string desp, com.amonsoft.exts.exts0001.ArrayOfBase64Binary file) {
            com.amonsoft.exts.exts0001.extsRequest inValue = new com.amonsoft.exts.exts0001.extsRequest();
            inValue.Body = new com.amonsoft.exts.exts0001.extsRequestBody();
            inValue.Body.user = user;
            inValue.Body.pwds = pwds;
            inValue.Body.exts = exts1;
            inValue.Body.mime = mime;
            inValue.Body.desp = desp;
            inValue.Body.file = file;
            com.amonsoft.exts.exts0001.extsResponse retVal = ((com.amonsoft.exts.exts0001.Exts0001Soap)(this)).exts(inValue);
            return retVal.Body.extsResult;
        }
    }
}
